# Generated by Django 2.1.4 on 2018-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20181219_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='Category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
