# Generated by Django 2.1.4 on 2018-12-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20181219_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
