# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-08 13:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restaurantlocation_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
